// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RUZWatcher.Data;

#nullable disable

namespace RUZWatcher.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("RUZWatcher.Models.UctovnaJednotka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AdresaMesto")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "mesto");

                    b.Property<string>("AdresaPSC")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "psc");

                    b.Property<string>("AdresaUlica")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ulica");

                    b.Property<DateTime?>("DatumVzniku")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "datumZalozenia");

                    b.Property<int>("Hodnotenie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazovSubjektu")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "nazovUJ");

                    b.Property<string>("Poznámka")
                        .HasColumnType("TEXT");

                    b.Property<string>("PravnaForma")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "pravnaForma");

                    b.HasKey("Id");

                    b.ToTable("UctovneJednotky");
                });

            modelBuilder.Entity("RUZWatcher.Models.UctovnaZavierka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("IdUJ")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "idUJ");

                    b.Property<string>("LinkPdf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rok")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "obdobieDo");

                    b.Property<string>("Typ")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "typ");

                    b.HasKey("Id");

                    b.HasIndex("IdUJ");

                    b.ToTable("UctovneZavierky");
                });

            modelBuilder.Entity("RUZWatcher.Models.UctovnaZavierka", b =>
                {
                    b.HasOne("RUZWatcher.Models.UctovnaJednotka", "UctovnaJednotka")
                        .WithMany("UctovneZavierky")
                        .HasForeignKey("IdUJ")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UctovnaJednotka");
                });

            modelBuilder.Entity("RUZWatcher.Models.UctovnaJednotka", b =>
                {
                    b.Navigation("UctovneZavierky");
                });
#pragma warning restore 612, 618
        }
    }
}
